- miriway-shell.config
Some bits are launched by systemd, so setting those there as well.
> Update systemd environment as well

- CMakeLists.txt
https://cmake.org/cmake/help/v3.5/module/GNUInstallDirs.html
Default values for the used variables:
- `CMAKE_INSTALL_BINDIR` -> `bin`
- `CMAKE_INSTALL_DATADIR` -> `share`
- `CMAKE_INSTALL_SYSCONFDIR` -> `etc`
> Use GNUInstallDirs variables for install destinations

- miriway_policy.cpp
- miriway_policy.h
Mir has implemented its own logic to doc windows, and that supports display reconfiguration. So let's use that instead of rolling our own.
Fixes: #12
> Rework docking of apps

- snap/snapcraft.yaml
This fixes the builds based on mir-libs. I've not isolated what things that were not staged are actually needed, as I don't think there's any reason to.
> Fix the mir-libs packaging

- miriway-shell.config
Having this set stops some GTK apps using the Wayland input methods we do support
> Unset GTK_IM_MODULE

- snap/snapcraft.yaml
Let the tooling decide if it needs another.
> snap: use the `/release` PPA by default

- miriway_commands.cpp
> Replace deprecated mir_keyboard_event_key_code

- miriway.cpp
- snap-utils/bin/miriway.vnc-server
Now we have `--shell-add-wayland-extension` we don't need to support as many by default.
> Drop some shell protocol extensions (now they can be enabled in configuration)

- miriway
- snap/hooks/install
It is a PITA to keep configs in step between snap and local installs of Miriway: The snap needs to specify where Xwayland is, local installs don't.
So, make use the Snap environment instead of the .config and the .config  can "just work" for both
> Make possible configs compatible between snap and non-snap installs

- miriway.cpp
Firefox C&P fails if the (unrelated) wp-primary-selection isn't enabled
> Workaround for Firefox bug

- example-configs/miriway-config-LXQT.bash
- example-configs/miriway-config-MATE.bash
- example-configs/miriway-config-SWAY.bash
- example-configs/miriway-config-XFCE.bash
- example-configs/miriway-config-alan_g.bash
Snapcraft no longer includes $SNAP/bin in PATH
Also tweaked the examples to handle when ~/.config dosn't exist
> Fix background

- snap/snapcraft.yaml
Mir has bumped libmiral6 to libmiral7 on `main`.
Ugly, but Snapcraft no longer uas try...else.
> Fix miriway/edge

- miriway.cpp
- If a shell component is dying ungracefully _and_ too quickly multiple times in a row, then we linearly throttle it to start later and later
- After 10 retries, we give up trying to keep it alive
**Question**: Can we set a timer in mir easily? I had to prepend to the event filter, which I don't like very much
> feature: throttling shell component restart

- miriway.cpp
1. Run Miriway with `./miriway --lockscreen-app=swaylock`
2. `loginctl lock-session <ID>`
3. Note that your session is locked
4. Enter your password in swaylock **or** `loginctl unlock-session <ID>` (**WARNING**: With `swaylock`, using `loginctl` to unlock will send you into a lockscreen-forever-loop, because Miriway sees swaylock exiting with status `2`, causing us to restart it over and over again. I have a pull request opened on that project to theoretically fix this)
5. Note that your session is unlocked
**WARNING**: This relies on this branch of Mir to work: https://github.com/canonical/mir/pull/3232
> feature: ability to specify a lockscreen app that gets run when the session is locked

- example-configs/miriway-config-LXQT.bash
- example-configs/miriway-config-MATE.bash
- example-configs/miriway-config-SWAY.bash
- example-configs/miriway-config-XFCE.bash
- example-configs/miriway-config-alan_g.bash
- snap/snapcraft.yaml
We can use shell components from the 24.04 archive that were not there from 22.04
> Use shell components from 24.04 archive

- CMakeLists.txt
- sddm/miriway.conf.in
This allows users to configure SDDM to use Miriway as a compositor, enabling a consistent experience from login into the desktop.
> Add option to install Miriway SDDM configuration

- miriway.cpp
This allows the location(s) searched for the `miriway-shell.config` to be adjusted.
For example:
MIRIWAY_CONFIG_DIR=lxqt cmake-build-debug/miriway
Will look in an `lxqt` subdirectory of the usual locations (e.g. `~/.config/lxqt`).
Fixes: #129
> Add MIRIWAY_CONFIG_DIR environment variable

- CMakeLists.txt
To stop the following warning from systemd:
```
machine # [   13.123163] systemd[906]: Configuration file /run/current-system/sw/share/systemd/user/miriway-session.target is marked executable. Please remove executable permission bits. Proceeding anyway.
```
> Install miriway-session.target without executable bits

- miriway_workspace_manager.cpp
- miriway_workspace_manager.h
With the implementation of xdg_activation_v1 in Mir 2.19 we can get "raise" requests from windows on hidden workspaces. We should switch workspace before giving these windows focus
> Activate the workspace for raised windows

- miriway-unsnap
- snap/snapcraft.yaml
This is the old issue of patchelf dropping the build-id, but this time it is the (internal to Mesa drivers) libgallium library that's SEGFAULTing when checking the build-id
Fixes: #145
> Update to work with Mesa-24.2

- miriway_ext_workspace_v1.cpp
- miriway_ext_workspace_v1.h
- miriway_workspace_manager.cpp
We were holding enough information to inform a new client (or a restarting one) of the active workspace
> track active workspace better

- miriway_ext_workspace_v1.cpp
Rework to avoid the need to synchronize workspace changes with the wayland thread
> Don't-own-workspaces-in-wayland

- CMakeLists.txt
Allows the xkbcommon includes to be found by pkgconfig on distributions that do non-standard things with their includes
> Add xkbcommon to target_include_libraries
